baseURL: "http://example.org/"

permalinks:
  posts: /:title/
  pages: /:title/

taxonomies:
  person: 'people'
  web_page: 'web_pages'
  post: 'posts'

params:
  uploads_dir: "/static/:title"
  _explore:
    groups:
      - heading: Collections
        collections:
          - web_pages
          - posts
          - people
      - heading: Website Management
        collections:
          - data
  _options:
    url:
      hidden: true
    content: &content_defaults
      uploads_dir: "/static/:title"
      width: 1920
      height: 1200
      format: p feature-heading h1 h2 h3 h4 h5 h6 div blue green yellow orange red pink purple black grey white
      # styles: /assets/css/custom-styles.css
      undo: true
      redo: true
      left: align-to-left
      center: align-to-center
      right: align-to-right
      justify: justify
      bold: true
      italic: true
      underline: true
      strike: true
      subscript: false
      superscript: false
      blockquote: true
      table: true
      code: true
      copyformatting: true
      removeformat: true
      numberedlist: true
      bulletedlist: true
      outdent: false
      indent: false
      image: true
      link: true
      embed: true
    content_html:
      *content_defaults
  _array_structures:
    page_sections:
      - label: Page Section
        icon: burst_mode
        value:
          label:
          section_heading:
          components:
    components:
      style: modal
      values:
        - label: Content Block
          icon: event_available
          image:
          value:
            _component_type: Content Block
            label: Content Block
            heading: Content Block
            content_html: